---
- name: Configure fg-crw servers
  hosts: fg-crw
  remote_user: ansible
  become: true

  vars:
    install_packages:
      - acl
      - net-tools
      - traceroute
      - wireguard
      - zabbix-agent
    backup_files:
      - /etc/hosts
      - /etc/hostname
      - /etc/resolv.conf
      - /etc/ssh/sshd_config
      - /etc/wireguard/*
      - /etc/netplan/*
      - /home/ansible/.ssh/authorized_keys
    backup_base_dir: /root/backup_configs
    max_backups: 10

  roles:
    - role: installation
      tags: [base, installation]
    - role: os-config
      tags: [base, os-config, firewall]
    - role: docker
      tags: [docker, app]
    - role: app
      tags: [app]
