---
- name: Create backup directory with timestamp
  ansible.builtin.shell: |
    timestamp=$(date +"%Y-%m-%d_%H-%M-%S")
    mkdir -p {{ backup_base_dir }}/${timestamp}
    echo ${timestamp}
  register: backup_timestamp
  changed_when: false

################################## OK ##################################
# - name: Copy important config files on remote host
#   ansible.builtin.shell: |
#     for f in /etc/hosts /etc/hostname /etc/resolv.conf /etc/ssh/sshd_config /etc/squid/squid.conf /etc/wireguard/wg1.conf /etc/netplan/50-cloud-init.yaml; do
#       if [ -f "$f" ]; then
#         cp "$f" {{ backup_base_dir }}/{{ backup_timestamp.stdout }}/
#       fi
#     done

##################################  ##################################

- name: Copy existing config files to backup folder
  ansible.builtin.shell: |
    for f in {{ backup_files | join(' ') }}; do
      if [ -f "$f" ]; then
        cp -r "$f" {{ backup_base_dir }}/{{ backup_timestamp.stdout }}/
      fi
    done

- name: Keep only the latest {{ max_backups }} backups
  ansible.builtin.shell: |
    cd {{ backup_base_dir }}
    ls -1dt */ | tail -n +{{ max_backups + 1 }} | xargs -r rm -rf
  changed_when: false
