---
- name: Copy Zabbix agent config
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: '0644'
  notify: Hey Handler! PLZ Restart zabbix-agent Service